### ISSUE TITLE
'Non-existent config key: FLAGS.CCROP' when training with KITTI dataset

### ISSUE THREAD

**Issue by XinruiGong** [karazijal/probable-motion#3]
Hello,
I met following problem when trained the network with KITTI dataset, could you please give me some suggestions to solve this problem?

vimb09@VISINF.LOCAL@lab20:~/probable-motion/src$ python main.py --config config_r18_kitti_wl.yaml UNSUPVIDSEG.DATASET KITTI
Attempting to enable deterministic cuDNN and cuBLAS operations to lvl 2 (Deterministic operations where available)
Traceback (most recent call last):
  File "/visinf/home/vimb09/probable-motion/src/main.py", line 311, in <module>
    main(args)
  File "/visinf/home/vimb09/probable-motion/src/main.py", line 132, in main
    cfg = setup(args)
  File "/visinf/home/vimb09/probable-motion/src/mask2former_trainer_video.py", line 295, in setup
    cfg.merge_from_file(args.config_file)
  File "/visinf/home/vimb09/anaconda3/envs/ppmp/lib/python3.9/site-packages/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/visinf/home/vimb09/anaconda3/envs/ppmp/lib/python3.9/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/visinf/home/vimb09/anaconda3/envs/ppmp/lib/python3.9/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/visinf/home/vimb09/anaconda3/envs/ppmp/lib/python3.9/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/visinf/home/vimb09/anaconda3/envs/ppmp/lib/python3.9/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
**KeyError: 'Non-existent config key: FLAGS.CCROP'**

Best,
Xinrui Gong

**Comment by karazijal** [comment]
Hi,

You can just remove the flag from the config. 

I forgot to remove it for Kitti dataset configs (the config flag was only moving clevrtex data, and we inlined the option to simplify for the release).
